
# List of Mass Bodies
masses:
  # Warning: indentation and hyphen (-) are required, even if there's only one
  # mass.
  - # coordinates from
    # choose one between [points, file_path]
    points: # list of points [x,y,z | lon,lat,h]
    file_path: "./geec/data/dem0.csv" # full path to file with mass body points
    density: 2670. # density of the mass body [kg m-3]
    gravity_constant: 6.67408e-11 # gravity constant [m3 kg−1 s−2]
    # topograpgy
    topo:
      is_topo: True # mass body is a topography structure
      water_density: 1025 # density of the water [kg m-3]
    # coordinates reference system
    crs:
      ref: ellps # [cart, enu, ellps] default: ellps (ellipsoid reference)

      # ellispoid parameters
      name: # default: 'wgs84'
      semimajor_axis: # [m]
      semiminor_axis: # [m]

      # Local ENU parameters (only if ref = enu)
      longitude_origin: # longitude relative to ellipsoid [degree east]
      latitude_origin:  # latitude relative to ellipsoid [degree north]
      altitude_origin:  # height above ellipsoid [m]

      # Geoid datum: Ellipsoid or Earth Gravitational Model [84,96,2008]
      # ellipsoid height (h) will be transform to orthometric height (H = h - geoid height)
      gdatum: egm96 # [ellps, egm84, egm96, egm2008] default: ellps (no change)

# Observers
observers:
  # coordinates from
  # choose one between [points, file_path, grid]
  points: [] # list of points [(x,y,z),(),..]
  file_path: # path to file with observation points
  grid:
    xstart_xend_xstep: [-10,11,1]
    ystart_yend_ystep: [-15,16,1]
    zstart_zend_zstep: [2000,2001,1]
  # coordinates reference system
  crs:
    ref: ellps # [cart, enu, ellps] default: ellps (ellipsoid reference)

    # ellispoid parameters
    name: # default: 'wgs84'
    semimajor_axis: # [m]
    semiminor_axis: # [m]

    # Local ENU parameters (only if ref = enu)
    longitude_origin: # longitude relative to ellipsoid [degree east]
    latitude_origin:  # latitude relative to ellipsoid [degree north]
    altitude_origin:  # height above ellipsoid [m]
